name: Publish

on:
  push:
    branches:
      - master

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ secrets.GIT_HUB_TOKEN }}
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Config Git
        run: |
          git config --local user.name "bot"
          git config --local user.email "bot@arcblock.io"

      - name: Init
        run: |
          pnpm install
          pnpm run build

      - name: Publish npm
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
          VERSION=$(cat version | awk '{$1=$1;print}')
          echo "publish version ${VERSION}"
          npm publish --access=public

      - name: Release
        run: make release
